# Generated by Django 4.2.15 on 2026-01-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medpem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kkm', models.IntegerField(default=75)),
            ],
            options={
                'verbose_name_plural': 'Pengaturan',
            },
        ),
    ]
