# Generated by Django 4.2.15 on 2026-01-16 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medpem', '0002_pengaturan'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilKuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kuis', models.IntegerField()),
                ('skor', models.IntegerField()),
                ('detail_jawaban', models.JSONField()),
                ('tanggal_pengerjaan', models.DateTimeField(auto_now_add=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_kuis', to='medpem.mahasiswa')),
            ],
            options={
                'ordering': ['-tanggal_pengerjaan'],
            },
        ),
    ]
