# Generated by Django 4.2.15 on 2026-01-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medpem', '0003_hasilkuis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasilkuis',
            name='detail_jawaban',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
