# Generated by Django 4.2.15 on 2026-01-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medpem', '0004_alter_hasilkuis_detail_jawaban'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilkuis',
            name='waktu_mulai',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilkuis',
            name='waktu_selesai',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hasilkuis',
            name='detail_jawaban',
            field=models.JSONField(default=list),
        ),
    ]
