# Generated by Django 4.2.15 on 2026-01-20 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medpem', '0005_hasilkuis_waktu_mulai_hasilkuis_waktu_selesai_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aktivitas',
            options={'ordering': ['materi__urutan', 'urutan'], 'verbose_name_plural': 'Aktivitas'},
        ),
        migrations.AlterModelOptions(
            name='hasilkuis',
            options={'ordering': ['-tanggal_pengerjaan'], 'verbose_name_plural': 'Hasil Kuis & Evaluasi'},
        ),
        migrations.AlterModelOptions(
            name='materi',
            options={'ordering': ['urutan'], 'verbose_name_plural': 'Materi'},
        ),
        migrations.AlterModelOptions(
            name='progresaktivitas',
            options={'verbose_name_plural': 'Progres Aktivitas'},
        ),
        migrations.RemoveField(
            model_name='progresaktivitas',
            name='tanggal_selesai',
        ),
        migrations.AddField(
            model_name='aktivitas',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='progresaktivitas',
            name='tgl_selesai',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hasilkuis',
            name='detail_jawaban',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='progresaktivitas',
            name='mahasiswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progres_aktivitas', to='medpem.mahasiswa'),
        ),
    ]
