# Generated by Django 4.2.15 on 2026-02-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medpem', '0006_alter_aktivitas_options_alter_hasilkuis_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Nama ini sudah terdaftar sebagai username.'}, help_text='Masukkan nama lengkap.', max_length=150, unique=True),
        ),
    ]
