# Generated by Django 4.2.15 on 2026-02-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medpem', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Username ini sudah terdaftar.'}, help_text='Username otomatis menggunakan email.', max_length=150, unique=True),
        ),
    ]
