# Generated by Django 4.2.15 on 2026-06-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medpem', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitas',
            name='durasi_menit',
            field=models.PositiveIntegerField(default=15, help_text='Durasi pengerjaan kuis dalam menit'),
        ),
    ]
