# Generated by Django 4.2.15 on 2026-06-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medpem', '0009_aktivitas_durasi_menit'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitas',
            name='kkm',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='aktivitas',
            name='durasi_menit',
            field=models.IntegerField(default=15),
        ),
    ]
