# Generated by Django 4.2.15 on 2026-06-04 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medpem', '0010_aktivitas_kkm_alter_aktivitas_durasi_menit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktivitas',
            name='durasi_menit',
        ),
        migrations.RemoveField(
            model_name='aktivitas',
            name='kkm',
        ),
        migrations.CreateModel(
            name='PengaturanKuisDosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kkm', models.IntegerField(default=75)),
                ('durasi_menit', models.IntegerField(default=30)),
                ('aktivitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medpem.aktivitas')),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengaturan_kuis', to='medpem.dosen')),
            ],
            options={
                'verbose_name_plural': 'Pengaturan Kuis Dosen',
                'unique_together': {('dosen', 'aktivitas')},
            },
        ),
    ]
