# Generated by Django 4.2.15 on 2026-06-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medpem', '0011_remove_aktivitas_durasi_menit_remove_aktivitas_kkm_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pengaturan',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Username ini sudah terdaftar.'}, max_length=150, unique=True),
        ),
    ]
