# Generated by Django 4.2.15 on 2026-06-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medpem', '0012_delete_pengaturan_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresaktivitas',
            name='tgl_selesai',
        ),
        migrations.AddField(
            model_name='progresaktivitas',
            name='tgl_akhir',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progresaktivitas',
            name='tgl_awal',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
