# Generated by Django 4.2.15 on 2026-07-04 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medpem', '0013_remove_progresaktivitas_tgl_selesai_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanKuisKelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kkm', models.IntegerField(default=75)),
                ('durasi_menit', models.IntegerField(default=30)),
                ('aktivitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medpem.aktivitas')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengaturan_kuis', to='medpem.kelas')),
            ],
            options={
                'verbose_name_plural': 'Pengaturan Kuis Kelas',
                'unique_together': {('kelas', 'aktivitas')},
            },
        ),
        migrations.DeleteModel(
            name='PengaturanKuisDosen',
        ),
    ]
