# Generated by Django 4.2.15 on 2026-07-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medpem', '0014_pengaturankuiskelas_delete_pengaturankuisdosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='angkatan',
            field=models.CharField(max_length=50),
        ),
    ]
